CREATE TABLE IF NOT EXISTS work_days (
  id INT NOT NULL AUTO_INCREMENT,
  date DATE NOT NULL,
  start_km INT NOT NULL,
  end_km INT DEFAULT NULL,
  fuel_own DECIMAL(10, 2) DEFAULT NULL,
  fuel_jose DECIMAL(10, 2) DEFAULT 0.00,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  status ENUM('OPEN', 'CLOSED') NOT NULL DEFAULT 'OPEN',
  PRIMARY KEY (id)
) ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
